### ISSUE TITLE
usage with docker-compose

### ISSUE THREAD

**Issue by stefangweichinger** [kumina/postfix_exporter#104]
Trying this:

```
# cat docker-compose.yml 
version: '3.7'

networks:
  back-tier:

services:

  postfix-exporter:
    image: chatwork/kumina-postfix-exporter:latest
    volumes:
      - /var/spool/postfix/public/showq:/var/spool/postfix/public/showq:ro
      - /var/log/mail.log:/var/log/mail.log:ro
    command:
      - '--web.listen-address=":9154"'
      - '--postfix.logfile_path="/var/log/mail.log"'
        #- '--systemd.enable'
    ports:
      - 9154:9154
    networks:
      - back-tier
        #restart: always
```

Getting:

```
# docker-compose up
[+] Running 2/2
 ⠿ Network postfix-exporter_back-tier             Created                                                                                                                                                                                 0.1s
 ⠿ Container postfix-exporter-postfix-exporter-1  Created                                                                                                                                                                                 0.1s
Attaching to postfix-exporter-postfix-exporter-1
postfix-exporter-postfix-exporter-1  | 2023/04/19 11:23:39 Reading log events from "/var/log/mail.log"
postfix-exporter-postfix-exporter-1  | 2023/04/19 11:23:39 Failed to create PostfixExporter: open "/var/log/mail.log": no such file or directory
postfix-exporter-postfix-exporter-1 exited with code 1
```

Tried to mount the directory `/var/log` also, same problem.

`/var/log/mail.log` exists on the host with read permissions. Help welcome ....

**Comment by maxkratz** [comment]
Not sure if this works nowadays, but on my old mail server, I've used this `docker-compose.yml` file to run the postfix exporter:
```
version: '3.2'

services:
  postfix-exporter:
    # use local Dockerfile to build image
    build: .
    # mount spool and logfiles as read only to container
    volumes:
      - /var/spool/postfix:/var/spool/postfix:ro
      - /var/log/mail.log:/var/log/mail.log:ro
    # map ports to host 
    ports:
      - 9154:9154
    restart: unless-stopped
```

Maybe this helps.
