### ISSUE TITLE
Prometheus config for postfix exporter

### ISSUE THREAD

**Issue by muscat-pl** [kumina/postfix_exporter#70]
Hi,
I'm looking for any ready config for postfix exporter for prometheus.yml but can't find anything.
Could anybody help me with that ?

**Comment by tokul** [comment]
It integrates same way as node exporter only port is different. Main problem is not configuring prometheus, but figuring how to convert fetched data into something useful.

  - job_name: 'Postfix'
    static_configs:
      - targets: ['hostname1:9154']
      - targets: ['hostname2:9154']

    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance

**Comment by maxkratz** [comment]
> Just remember yml layout as you see messed up layout in this post.

You can use multiline code blocks here :).

```
- job_name: 'Postfix'
  static_configs:
    - targets: ['hostname1:9154']
    - targets: ['hostname2:9154']
  
  relabel_configs:
    - source_labels: [__address__]
    regex: "([^:]+):\\d+"
    target_label: instance
```
